project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - awards.qmd
      - publications.qmd
      - presentations.qmd
    tools:  
      - icon: github
        href: https://github.com/peilun-he
      - icon: linkedin
        href: https://www.linkedin.com/in/peilunhe/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    grid: 
      sidebar-width: 100px
      body-width: 1300px
      margin-width: 100px 
      gutter-width: 1.5rem

editor: visual

